@host = localhost:8080
@baseUrl = http://{{host}}
@contentType = application/json

### health check
GET {{baseUrl}}/ping
Accept: {{contentType}}


### Variable in request body
@email = user@example.com
@password = secret


POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}
