@host = localhost:8080
@baseUrl = http://{{host}}
@contentType = application/json

### Signup
@email = user@example.com
@password = secret
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Signin — captura o token
@email = user@example.com
@password = secret
POST {{baseUrl}}/auth/signin
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("access_token", response.body.data.access_token);
%}

### Health check — usa o token capturado acima
GET {{baseUrl}}/ping
Accept: {{contentType}}
Authorization: Bearer {{access_token}}



### 1. Signin
POST {{baseUrl}}/auth/signin
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("access_token", response.body.data.access_token);
%}
